In [ ]:
import numpy as np

## Creacion de arrays basicos

In [ ]:
# creamos un numpy arrray
np. array([10,20,24,5,15,50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
# Accedemos a los elementos con indicies
a = np.array([1,3,4,23,45,76,898,89,45])
a[4]

45

In [ ]:
# Usando slices
a[3:7]

array([ 23,  45,  76, 898])

In [ ]:
# Slices con pasos
a[1::3]

array([ 3, 45, 89])

## Crear arreglos dinamicos

In [ ]:
# Creamos array de ceros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Creamos una matriz de ceros
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# una matriz unitaria
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Una matriz con cualquier full con cualquier otro valor
np.full((4,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
# Matriz Diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# Espacio lineal (inicio, fin, tamaño de paso)
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Array 2d o matriz con strings
b = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
print(b)
type(b)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


numpy.ndarray

In [ ]:
# Dimensiones (1d, 2d, 3d)
b.ndim

2

In [ ]:
b.shape

(2, 3)

## Ordenando Arrays

In [ ]:
c = [12,3,5,6,1]
np.sort(c)

array([ 1,  3,  5,  6, 12])

In [ ]:
type(c)

list

## Datos con semi tabulados con cabeceras

In [ ]:
cabeceras =  [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]

# Creamos el arreglo
usuarios = np.array(datos, dtype=cabeceras)

# Hacemos sort de los datos
np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

## Rangos de numeros con Arange

In [ ]:
# Creando un rango de nuevos
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Esto funciona como range normal
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Reto crear un arreglo de 3 dimensiones y ordenarlo por edad 

In [ ]:
cabeceras2 =  [('nombre', 'S10'), ('edad', int), ('pais', 'S10')]
datos2 = [
          [[('Juan', 10, 'MEX'), ('Maria', 40, 'COL'), ('Javier', 42, 'COL')]], 
          [[('Samuel', 15, 'MEX'),('David', 12, 'USA'), ('Ada', 17, 'COL')]], 
          [[('Tony', 22, 'COL'), ('Rusbel', 33, 'MEX'), ('Frida', 18, 'USA')]]
        ]

# Creamos el arreglo
usuarios2 = np.array(datos2, dtype=cabeceras2)
usuarios2.ndim

3

In [ ]:
print(usuarios2)

[[[(b'Juan', 10, b'MEX') (b'Maria', 40, b'COL') (b'Javier', 42, b'COL')]]

 [[(b'Samuel', 15, b'MEX') (b'David', 12, b'USA') (b'Ada', 17, b'COL')]]

 [[(b'Tony', 22, b'COL') (b'Rusbel', 33, b'MEX') (b'Frida', 18, b'USA')]]]


In [79]:
COL = 0
DIM0 = 3
usuarios2[:, usuarios2[:, :, COL].argsort()][np.diag_indices(DIM0)]

array([[[(b'Juan', 10, b'MEX'), (b'Maria', 40, b'COL'),
         (b'Javier', 42, b'COL')]],

       [[(b'Samuel', 15, b'MEX'), (b'David', 12, b'USA'),
         (b'Ada', 17, b'COL')]],

       [[(b'Tony', 22, b'COL'), (b'Rusbel', 33, b'MEX'),
         (b'Frida', 18, b'USA')]]],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])